### PR TITLE
New Minigame

### PR DESCRIPTION
**Pull request by paolovalerdi**
Another meteor shower game, but in this one the bombs fall randomly

### CODE REVIEW

**Comment by GnidGnaw** [comment]
Isn't this just Eisregen that Eric wrote

**Comment by paolovalerdi** [comment]
What do you mean with Eisregen?

**Comment by paolovalerdi** [comment]
If Eisregen means "ice rain", no it is not the same. In this one can fall ice, normal, sticky or impact bombs, not just one type of bomb

**Comment by GnidGnaw** [comment]
Eisregen is the random bomb meteor shower game

**Comment by paolovalerdi** [comment]
I have never heard about it. I tried to find one like that, I couldn't find it so I just wrote some lines in the normal game

**Comment by GnidGnaw** [comment]
anyways, your implementation is quite good

**Comment by Mrmaxmeier** [comment]
@paolovalerdi Thanks for contributing!

**Pull request merged**
